### ISSUE TITLE
Recipe request: character/word count of currently selected text

### ISSUE THREAD

**Issue by a-dg** [richie5um/TextBar-Recipes#1]
This would be incredibly useful. Not sure if it's possible.

**Comment by richie5um** [comment]
I thought it might be possible to get this using AppleScript. But, as AppleScript isn't supported in all apps, I couldn't get it working. Would love to know if you do find a way though!

I doubt it is what you want, but, if you wanted to get the character count of the current clipboard text, you can use this: 

    pbpaste | wc -c

**Comment by a-dg** [comment]
An excellent solution, thanks!
