### ISSUE TITLE
Launch TextBar at startup

### ISSUE THREAD

**Issue by microspino** [richie5um/TextBar-Recipes#10]
Which is the proper way to launch your **veeeeery nice app** at startup?
I'm on OS X 10.10.3.

**Comment by richie5um** [comment]
Thank you :-)

The quick and easy way to do this is to:
* Start ‘System Preferences’
* Select ‘Users & Groups’
* Select your user
* Select ‘Login Items’
* Then add ‘TextBar’ to this list.

I’ve added a screenshot of mine so hopefully the above steps make sense.

-Rich
