### ISSUE TITLE
Finder item info?

### ISSUE THREAD

**Issue by greatoe** [richie5um/TextBar-Recipes#11]
Hi I'm new here and I don't know if this is the place to ask for features, forgive me if not.

Is it possible to display information of  current selected Finder item?
Like file size, assigned tags, spotlight comment, item count of a folder ... ?

**Comment by richie5um** [comment]
I’ve added a script to do this.
https://github.com/richie5um/TextBar-Recipes#show-selected-file-in-finder <https://github.com/richie5um/TextBar-Recipes#show-selected-file-in-finder>

Let me know if you need any help to get this working.

-Rich

**Comment by greatoe** [comment]
works perfect, thanks.

I managed to modify a little bit your script (pity I know just very very few coding) and I can display file size in kb and spotlight comments now.
Trying to display pixel width and height of image file.
And maybe tags also ...

**Comment by richie5um** [comment]
Hi,

Excellent, great work. :-)

-Rich
