### ISSUE TITLE
HTML doesn't work with latest update (v1.5.184)

### ISSUE THREAD

**Issue by ctwise** [richie5um/TextBar-Recipes#15]
HTML no longer works with v1.5.184. It shows as text in the dropdown menu. Presumably the new multi-line support has killed the HTML support.

**Comment by richie5um** [comment]
Hi Charles,

Thanks. I'll investigate and get it fixed asap.

-Rich

**Comment by richie5um** [comment]
Can you send me a screenshot?

**Comment by ctwise** [comment]
[image: Inline image 1]

**Comment by ctwise** [comment]
Here's the entire output of the shell script:

<html>
  <head>
    <style type="text/css">
      body {
        font-size: 12px;
        font-family: Helvetica Neue, sans-serif;
        color: white;
      }
      .p1 {
        vertical-align: 4px;
      }
    </style>
  </head>
  <body>
      <span class="p1">wisehomen</span>
  </body>
</html>

**Comment by richie5um** [comment]
Sorry for the delay in responding.

Ah, yes. I see what you mean. My HTML tests were all on a single line. I've merged your script to be just a single line and it works.

I'll update the handling logic to allow HTML over multiple lines.

Thanks.

**Comment by richie5um** [comment]
This is now resolved in 1.5.210 - use 'Check for Updates' to force the update.

Separately...

I don't seem to be able to get HTML multi-line output working. The Apple frameworks don't allow me to understand HTML as multilines.

And, I wish I could fix the text vertical alignment. I'm working on finding a way to do it - so you don't have to resort to HTML to modify it.

**Comment by richie5um** [comment]
By the way, many thanks for the bug report! :-)

**Comment by richie5um** [comment]
Hi,

I think I may have fixed the text vertical alignment issue. There isn't a clean way of doing it, but, I think I've managed to trick the system into aligning it for me.

I have a provision build available if you want to try it. Steps:
* Exit TextBar
* Download (http://www.richsomerfield.com/apps/textbar/TextBar.app-1.5.234.zip) and copy the TextBar.app to your applications folder
* Run this in Terminal 'defaults write com.RichSomerfield.TextBar DefaultVerticalAdjustor -bool YES'
* Start TextBar

Note: This version will still automatically upgrade as I make newer versions available.

To disable the vertical override logic:
* Exit TextBar
* Run this in Terminal 'defaults delete com.RichSomerfield.TextBar DefaultVerticalAdjustor'
* Start TextBar

-Rich

**Comment by ctwise** [comment]
That adjusts the text _too_ high. :-) One step forward...

**Comment by richie5um** [comment]
Closing the original issue. The text layout saga continues...
