### ISSUE TITLE
Finder item tags?

### ISSUE THREAD

**Issue by greatoe** [richie5um/TextBar-Recipes#17]
May I ask for a recipe to display the tags of the current selected Finder item?

**Comment by richie5um** [comment]
I've added a new script called ''SelectedFinderFile-ShowTags.scpt", use it in the same way as the instructions for "SelectedFinderFile.scpt".

Unfortunately, if a file has multiple colors, it'll only show one of them via this script. I don't seem to be able to find a way to get all of the colors. Perhaps someone else will see this and be able to help.

**Comment by greatoe** [comment]
Thank you.
