### ISSUE TITLE
Check MySQL Status Not Working On Mac

### ISSUE THREAD

**Issue by debbbbie** [richie5um/TextBar-Recipes#18]
my scripts of checking mysql is not working:
```
mysql.server status | grep -q SUCCESS && echo "MySQL Runing" || echo "MySQL Dead"
```

while my scripts of checking memcached is working:
```
ps awx|grep -v grep |grep -q memcached  && echo "Memcached Running" || grep "Memcached Dead"
```

**Comment by debbbbie** [comment]
ps awx|grep -v grep | grep -q mysqld_safe && echo "MySQL Runing" || echo "MySQL Dead"

It works!

**Comment by richie5um** [comment]
Yay! Thanks. I'll add it to the main page.

With recent versions of TextBar you can add colors too, e.g.:
ps awx|grep -v grep |grep -q memcached  && echo "Memcached \e[92mRunning\e[39m" || echo "Memcached \e[91mDead\e[39m"

![screen shot 2015-05-22 at 12 33 04](https://cloud.githubusercontent.com/assets/907033/7769740/bb1a6884-007e-11e5-832b-f5f6c0b10811.png)

**Comment by debbbbie** [comment]
:+1:
