### ISSUE TITLE
Shortcut key to refresh

### ISSUE THREAD

**Issue by leocrespo** [richie5um/TextBar-Recipes#30]
This app needs a shortcut key to refresh all, or maybe a command in terminal, applescript I don't know, something that would tell it to refresh all. If I have something that updates every 5 minutes and I just manually change it, I would like to trigger a refresh immediately.

Currently I have to do an awkward applescript to click the icon on the menubar. http://cl.ly/0Q112X1D0319 

I think that would be very useful. Thanks for considering.

**Comment by leocrespo** [comment]
Nothing?

**Comment by richie5um** [comment]
Sorry, thought I'd replied to this on UserVoice. Yes, the app needs a refresh. I'm working on a v2 (with a brand new UI), but that has slowed me down a fair bit. I'll see what I can pull together to add sooner to v1.

Rich

**Comment by richie5um** [comment]
Hi, I've added (basic) AppleScript support to v1.10.1. Using this you can set up a shortcut key to refresh the scripts

Like this:
![textbarrefresh](https://cloud.githubusercontent.com/assets/907033/14193237/0a4ad65a-f79b-11e5-934c-4965f93f6022.png)

**Comment by leocrespo** [comment]
Thank you but it doesn't seem to work. 
http://d.pr/i/1lnRD.png
http://d.pr/i/1cLRr.png
http://d.pr/i/1arpF.png
http://d.pr/i/T7hU.png

also wasn't this supposed to work?
http://d.pr/i/jHBe.png

**Comment by leocrespo** [comment]
Is there any plan to make this work please?

**Comment by leocrespo** [comment]
Possibly the reason this isn't workign is that you don't provide any download links for the newer version. The only version that can be downloaded from your site is 1.9.6 

v1.10.19

Added better defaults for fonts in HTML handler (dark-mode based color & system font).
v1.10.1

Added basic AppleScript support (Refresh/RefreshIndex/ItemCount).
v1.9.6

Updating Sparkle to latest version.
Added Apple ATS bypass - to allow your scripts to work.
Added dynamic refresh time control - via Action script.
Updated app update to use HTTPS.

**Comment by richie5um** [comment]
Sorry for the slow turn-around on this, I've had a major issue at my day job to sort out. Hopefully I'll be able to investigate this tonight.

The newer version should update automatically through the menu for TextBar > Check for updates. Does that work?

**Comment by leocrespo** [comment]
No worries. It doesn't update though. If you could just put the link for the current version on your site that would be great.

**Comment by richie5um** [comment]
I've updated the main download page to be the latest version (1.10.19). Do you have this version? Are you still having issues with the AppleScript support?

**Comment by leocrespo** [comment]
Yes man all working fine now, thanks heaps! :)

**Comment by richie5um** [comment]
Phew, great :-).

Let me know if there is anything else you have issues with - and I'll try and not be as slow at responding. ;-)

Have a great weekend.

Rich

**Comment by warthurton** [comment]
Suggest closing.  Issue is resolved.
