### ISSUE TITLE
Error messages in Console

### ISSUE THREAD

**Issue by betalogue** [richie5um/TextBar-Recipes#31]
Getting 2-4 messages like this one PER SECOND in the system log:

16-04-28 10:56:33,873 TextBar[83064]: Remove Temp: Error Domain=NSCocoaErrorDomain Code=4 "“FA17D00F-C1EE-449F-A4F2-6F310D94C255-83064-000189A14AE67365” couldn’t be removed." UserInfo={NSFilePath=/var/folders/sp/fgbr368s4_q5_rbzb_4k5w740000gn/T/FA17D00F-C1EE-449F-A4F2-6F310D94C255-83064-000189A14AE67365, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7f9b19c42a30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

What can I do to stop this?

Thanks.

**Comment by richie5um** [comment]
Sorry. I need to fix this. I'll get it sorted asap.

Regards,
Rich
