### ISSUE TITLE
Impossible to see text

### ISSUE THREAD

**Issue by m-thomson** [richie5um/TextBar-Recipes#32]
When editing my script the text color changes to white on white. In the screenshot, you can see it only because I've highlighted everything (CMD+A). It makes inline editing impossible (need to copy+paste from elsewhere. Thanks!
<img width="769" alt="screenshot_screenshot_46f83 png" src="https://cloud.githubusercontent.com/assets/5273016/16602111/6e8e6f66-42c6-11e6-89ba-3339c526f1f0.png">

**Comment by richie5um** [comment]
Thanks. I've noticed this too - it only happens some times on my machine. Oddly, if you click on the text, then click away, then click back on the text, it shows in the correct color.

I'll investigate and see if I can fix.

-Rich

**Comment by richie5um** [comment]
If you update to v1.10.94, this should now be resolved. Thanks.

**Comment by m-thomson** [comment]
Great! Thanks for the quick turn around.
