### ISSUE TITLE
Write smth to Menubar

### ISSUE THREAD

**Issue by gerritgriebel** [richie5um/TextBar-Recipes#36]
I was installing TextBar because I thought it must be able make some text appear using AppleScript or shell. Do I really have to do "echo TextToAppear > /tmp/textbar" and then periodically poll "cat /tmp/textbar"? Is there a smarter way to do it? Is it a feature request? :)

**Comment by richie5um** [comment]
I may have misunderstood what you mean, but you can just do 'echo
TextToAppear' in TextBar. Or "$HOME/bin/myscript.sh". Or "osascript -e
'...'". Hope this answers your question.

**Comment by gerritgriebel** [comment]
I'd like to write text to the menu bar within a Keyboard Maestro Macro. The macro is triggered by a keystroke, to by textBar itself.

**Comment by richie5um** [comment]
Ah. I added AppleScript support to TextBar a few releases ago. It seems to mostly work, although I've never really mentioned / documented it. I've attached a quick script to refresh all items. You can also refresh a specific one. Let me know if this works.


[TextBarScript.scpt.zip](https://github.com/richie5um/TextBar-Recipes/files/590534/TextBarScript.scpt.zip)

**Comment by gerritgriebel** [comment]
```
tell application "TextBar"
	refreshAll
	refreshIndex 0
	enabledItemCount
end tell
```
Works, thanks a lot! Now I get around polling and waiting for the text to appear.

What "enabledItemCount" good for?

PS: Still, it would be even nicer, if AppleScript calls would allow to write text directly to an TextBar item without the need of an intermediate file. Such an item would have no script and no refresh (secs). Maybe smth to consider for future releases?

**Comment by richie5um** [comment]
As items can be enabled/disabled (in the TextBar Preferences) - this means you can either use the enabled index, or, the overall index.

I'll look to add the ability to set the text - but, might have to re-think some things as when the script does 'refresh' it would overwrite it. Will have a think.
