### ISSUE TITLE
License activation error

### ISSUE THREAD

**Issue by iAurora** [richie5um/TextBar-Recipes#37]
Can't activate the license after OS re-install. Been trying for few days now with and without VPN to make sure it's not blocked on a country level.

![monosnap 2016-12-12 11-28-18](https://cloud.githubusercontent.com/assets/347206/21092584/523dfdfc-c05e-11e6-8668-c3b2fc44c257.png)

**Comment by richie5um** [comment]
Sorry you are having problems.

The licensing is handled for me by Paddle.com. I'll contact them for you to determine if this is a known issue.

Regards,
Rich

**Comment by iAurora** [comment]
I have found the issue now. Blocked Paddle Api by accident. All works now. 
Sorry for taking your time and thanks for a great little app.
