### ISSUE TITLE
Another weather recipe

### ISSUE THREAD

**Issue by r--w** [richie5um/TextBar-Recipes#4]
Just change location:

```
echo `curl -s 'http://api.openweathermap.org/data/2.5/weather?q=Poznan,pl&units=metric'  | python -c 'import sys, json; print round(json.load(sys.stdin)["main"]["temp"], 1)'`°C
```

Final:
![screenshot at kwi 24 12-16-11](https://cloud.githubusercontent.com/assets/1191700/7316950/b9efa0b4-ea7b-11e4-9ccf-fdb38309f5e0.png)

**Comment by richie5um** [comment]
Thank you. I’ve made a slight improvement (to also print the conditions, i.e. “Clouds") .

Many thanks for the suggestion!!

curl -s 'http://api.openweathermap.org/data/2.5/weather?q=Manchester,UK&units=metric' | python -c 'import sys, json; data=json.load(sys.stdin); print("{} : {:.1f}°C".format(data["weather"][0]["main"], data["main"]["temp"]))'

-Rich
