### ISSUE TITLE
After Upgrading to 3.0.369 Names are shown as "item"

### ISSUE THREAD

**Issue by reibejoy** [richie5um/TextBar-Recipes#45]
I just updated to the latest version and all my items have been renamed to "item" 

![safari technology previewscreen shot 21 oct 2017 at 11 54 40](https://user-images.githubusercontent.com/2094721/31850689-ead7a06a-b656-11e7-9308-f4fe041eb483.png)

**Comment by richie5um** [comment]
Yes. Unfortunately TextBar v2 didn’t have ‘names’ so I had to automatically add something. You can use this to describe what that TextBar item is used for. 

Hope this makes sense.
