### ISSUE TITLE
Shell and shell arguments not saved

### ISSUE THREAD

**Issue by lucajovine** [richie5um/TextBar-Recipes#47]
Hello, I use tcsh as default shell on my system, and so TextBar automatically sets the shell to that; moreover, it selects "-l" as default argument, with the result that none of the standard scripts etc. work. If I manually specify /bin/sh in the Advanced Preferences, and delete "-l", then everything works... but these new values are not stored. So upon reboot I'm back to square one. How to get TextBar to remember my choices?
I am using version 3.2.2, and High Sierra 10.13.1.
Thanks, Luca

PS: This command also seems to have no effect:

defaults write com.RichSomerfield.TextBar DefaultShell -string "/bin/sh"

**Comment by richie5um** [comment]
Oops, sorry. I’ll fix this ASAP.

**Comment by richie5um** [comment]
Really sorry for the inconvenience. I think I've fixed this in v3.2.20 (use 'Check for updates' to force the update).

FWIW, I'd rushed a fix for an issue with the 'default' button not updating the UI, but that caused the initialisation logic to ignore your customisations. Hopefully this should all work correctly now.

**Comment by lucajovine** [comment]
Wow, talk about a fast response! Thanks a million, now it works just fine :-)
