### ISSUE TITLE
error when registering "License code has already been utilized"

### ISSUE THREAD

**Issue by ghost** [richie5um/TextBar-Recipes#49]
Obviously, I bought the license. I'm installing it in a new computer, what sort of error is this?

**Comment by richie5um** [comment]
Sorry you are having problems. 

Did you just purchase this license (and have never used it before), or is it an existing license? If you send me your email (either post it here, or, email it to rs@richsomerfield.com), I can track it down. And, if that doesn't work, I'll just create you a new license.
