### ISSUE TITLE
Script path containing ~ issue

### ISSUE THREAD

**Issue by iAurora** [richie5um/TextBar-Recipes#51]
For some weird reason the file picker replaces the ~ in the path with $HOME like this:

`$HOME/Library/Mobile\ Documents/com~apple~CloudDocs/config/textbar/mail.sh` --->
`$HOME/Library/Mobile\ Documents/com$HOMEapple$HOMECloudDocs/config/textbar/mail.sh`

So naturally Textbar fails to find the script and ends up not displaying a thing.

It wasn't an issue before, because I just took a working item with a script located in the same folder and re-picked the file. It no longer works.

**Comment by richie5um** [comment]
D'oh. Thanks for the detail, that _should_ be a quick fix. I'll look at it tonight.

**Comment by richie5um** [comment]
Please can you try this updated version and let me know: http://richsomerfield.com/apps/textbar/TextBar.app-3.2.152.zip

Thank you.

**Comment by iAurora** [comment]
That seems to have fixed it. Thanks!

**Comment by richie5um** [comment]
Great. I'll make this version available to everyone later today.

Please raise any issues (or suggestions) you find. 

Thanks.
