### ISSUE TITLE
Restore TextBar from time capsule backup

### ISSUE THREAD

**Issue by reibejoy** [richie5um/TextBar-Recipes#52]
Hi, 

How can I restore textbar from a time capsule backup? Which folders are needed? 
Problems that I currently have after a necessary reset on my machine:

- license is missing (can't find the e-mail either .. )
- my old rules are missing 

Thanks in advance. 

best, 
Jan

**Comment by reibejoy** [comment]
I found a solution for the license (got it from paddle) 

Unfortunately no answer on where the rules / scripts are stored. 
Well, maybe the author lost interest.

**Comment by richie5um** [comment]
Hey. Really sorry I forgot to reply.

Glad you got it sorted, but not good enough from me. Can I offer you some free licenses for you to give out to friends?

The file you need to restore is:
~/Library/Preferences/com.RichSomerfield.TextBar.plist

If you have used any new 'imported' scripts. They are stored in:
~/Library/Application Application\ Support/com.RichSomerfield.TextBar

**Comment by gustafekeberg** [comment]
This is useful to solve the problem in issue [#56](https://github.com/richie5um/TextBar-Recipes/issues/56).
