### ISSUE TITLE
Textbar ask for permissions to use the microphone

### ISSUE THREAD

**Issue by Fischmuetze** [richie5um/TextBar-Recipes#55]
Mojave 10.14.1
Several Macs ...

Any idea why asking Textbar for permissions to use the microphone? 
I wonder since I have no shell scripts, programs nor any other objects placed in Textbar which could challenge that.
[
![bildschirmfoto 2018-10-28 um 16 34 23](https://user-images.githubusercontent.com/19834496/48028663-600c8f00-e14c-11e8-84b1-08980aba1c4a.png)
](url)

**Comment by richie5um** [comment]
I've no idea why it would. I don't do anything with the microphone - other than anything someone has configured in their script.

I'm currently running 10.14.0. I will try to run it on 10.14.1 to see if this is something new with Mojave.

Regards,
Rich

**Comment by richie5um** [comment]
Do you still see this? I don't.

**Comment by Fischmuetze** [comment]
Dear Rich,
I don't know if the issue is gone or alway persistent since I can't reproduce it without uninstall Textbar - which I would not prefer.
Unfortunately Apple have still not implemented a button to remove a rule.

Cheers
Steffen
