### ISSUE TITLE
No icons in menubar

### ISSUE THREAD

**Issue by gustafekeberg** [richie5um/TextBar-Recipes#56]
My TextBar don't show any icons in the menubar. I guess that there is one recipe that's causing this bug. The problem is that I can't disable any of my recipes when there is no icons. How can I reset TextBar?

**Comment by richie5um** [comment]
Hi. There is a default you can set to force show the default TextBar icon. I thought I’d documented on the README page, but I can’t find it. I’ll find the instructions and send them over.

**Comment by richie5um** [comment]
Usually when this happens, there is a *very* thin, and transparent part of your menubar where the TextBar menu item is.

However, the workaround is to:
* Close TextBar (or, quit it in Activity Monitor)
* Run this in your terminal: defaults write com.richsomerfield.textbar DisableItemsOnStart -bool true
* Start TextBar

If all has worked, you should get the TextBar icon in your menubar. All the textbar items will be disabled, and you'll need to reenable them.

To stop this 'auto-disable' behaviour, run this:
* defaults delete com.richsomerfield.textbar DisableItemsOnStart

**Comment by richie5um** [comment]
Let me know if this doesn't work.

**Comment by gustafekeberg** [comment]
It doesn't work. A bunch of other icons (other applications) disappear as well.

**Comment by gustafekeberg** [comment]
Removing ~/Library/Preferences/com.RichSomerfield.TextBar.plist will make TextBar work again if nothing else works. All the recipes need to be restored manually.
