### ISSUE TITLE
Cannot get action trigger to work in menu bar

### ISSUE THREAD

**Issue by mwoffenden** [richie5um/TextBar-Recipes#57]
I'm following: https://github.com/richie5um/TextBar-Recipes#actions and trying to create the example https://github.com/richie5um/TextBar-Recipes#actions.

It's not working on MacOS 10.14.4.

What am I missing?

**Comment by richie5um** [comment]
I’ll take a look and get back to you.

**Comment by richie5um** [comment]
Did you try this one?
https://github.com/richie5um/TextBar-Recipes#quick-finder-launcher-example

I got a prompt, but after I'd accepted that, it worked correctly. I'm on 10.14.4.
![image](https://user-images.githubusercontent.com/907033/57065143-70975f80-6cc0-11e9-93fd-78aff702d49a.png)

Did it used to work on a previous version?

**Comment by mwoffenden** [comment]
I've requested a refund, thank you.
