### ISSUE TITLE
How to display the title of an active tab in Safari in menubar?

### ISSUE THREAD

**Issue by eshill** [richie5um/TextBar-Recipes#58]

**Comment by richie5um** [comment]
Create a TextBar item with a script of...

osascript -e 'tell application "Safari" to return name of front document'

You'll need to set a sensible refresh time :)

**Comment by eshill** [comment]
SUPER!!!! 
Thanx.

**Comment by eshill** [comment]
And how do you make it work in other browsers? Like Chrome?

**Comment by richie5um** [comment]
You can do it like this, but this obviously doesn't work well if you have multiple chrome windows open.

`osascript -e 'tell application "Chrome" to return name of active tab of window 1'`

**Comment by Khilkov** [comment]
Thank you very much!

**Comment by eshill** [comment]
thank you very much!

**Comment by eshill** [comment]
Another question ))
Can I make some layout changes using CSS custom styles?

For example, change the background color of the site that opens in the TextBar window.

**Comment by richie5um** [comment]
I guess that depends on whether you control the HTML code for it - in which case you can just change that. It you don't control the web site, then I don't think you'll be able to do it. HTH.
