### ISSUE TITLE
External keyboard / mouse battery monitor recipe

### ISSUE THREAD

**Issue by r--w** [richie5um/TextBar-Recipes#6]
Mouse: 
```
echo "M: "`ioreg -c BNBMouseDevice | grep '"BatteryPercent" ='  |  sed 's/[^0-9]*//g'`"%"
```
Keyboard: 
```
echo "K:" `ioreg -c AppleBluetoothHIDKeyboard | grep '"BatteryPercent" ='  | sed 's/[^0-9]*//g'`"%"
```

Final:
![screenshot at kwi 24 12-14-06](https://cloud.githubusercontent.com/assets/1191700/7316904/71329462-ea7b-11e4-844f-0cef816d9bbe.png)

**Comment by richie5um** [comment]
OMG. Awesome idea!

I’ll merge your pull request later on.

Thanks.

-Rich
