### ISSUE TITLE
Support for standard macOS icons via SF Symbols font?

### ISSUE THREAD

**Issue by gingerbeardman** [richie5um/TextBar-Recipes#60]
https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/

**Comment by richie5um** [comment]
Looks like they are, currently, not available on macOS.

TextBar still supports 10.10, so that might cause issues too.

Thanks for the link.

**Comment by gingerbeardman** [comment]
Download is here: https://developer.apple.com/design/resources/#馬鹿っ花-symbols

But: macOS 10.14.4 or later (55.3 MB)
