### ISSUE TITLE
No textbar under last Catalina beta

### ISSUE THREAD

**Issue by tatecapone** [richie5um/TextBar-Recipes#61]
Just this...the app doesnt open.

**Comment by richie5um** [comment]
Do you have the latest version of textbar? I added notarized last week.

**Comment by tatecapone** [comment]
Yes….I have the latest version…3.2.182…and Catalina 10.15 Beta (19A573a)...



2019-09-30 16:24:20 +0000 Rich Somerfield <notifications@github.com> :

**Comment by richie5um** [comment]
Thanks. 

if you open console.app, does it show a reason for it not starting?

**Comment by tatecapone** [comment]
ok..is very odd..I restart Catalina and now textbar work perfectly...sorry
for the absurd nuisance


2019-09-30 18:39:36 +0000 Rich Somerfield <notifications@github.com> :

**Comment by richie5um** [comment]
Phew :)

thanks for letting me know
