### ISSUE TITLE
Timeout for scripts?

### ISSUE THREAD

**Issue by bcjordan** [richie5um/TextBar-Recipes#62]
Most of my scripts work well, but I have a single-line long-running script (15-20 seconds) that works well in terminal, but only outputs a `.` on the text-bar. 

Is there a default timeout for the one-line scripts? Would making it a full recipe possibly make it work?

**Comment by richie5um** [comment]
A long running script shouldn't be a problem. But, the TextBar item won't show anything new until the entire script has completed - the '.' is the default text to show before a script has completed for the first time. There may be something in your script that is causing TextBar problems. If you open 'Console.app' and search for TextBar, you may be able to figure it out.



There is an alternative approach to showing data in TextBar that may be more suitable for you - it creates a web listener in TextBar, and then your external script can send data directly to it (TextBar shows the data whenever it is sent - so you can update as your script runs). You'll need to figure out a way to run your script though - you could use a different TextBar item to do that, but in itself don't output anything.

It may be over complicating things, but, this is how to do it...

 * Create a TextBar item called 'Sender' (this is your long running script), something like this...
   * This will cause a very small blank area on your MenuBar
echo "" && curl -d "$(date)" localhost:8999


 * Create a TextBar item called 'Listener' (this is what displays the text in TextBar). This special script syntax creates a web listener on the specified port...

That then looks like this...

**Comment by bcjordan** [comment]
Thanks for the info, will close this!

**Comment by richie5um** [comment]
Let me know how you resolve your issue - so I know for the future :)
