### ISSUE TITLE
Lost Licence service

### ISSUE THREAD

**Issue by reibejoy** [richie5um/TextBar-Recipes#63]
Ever after upgrading to Catalina I am greeted by the "enter licence" dialogue in textbar. I purchased it and it was working prior to updating. I just can't find my licence any more. I must've forgotten to save it to where I usually save my licenses. 

So I'm looking for a way to retrieve my licence. Any help would be appreciated.

**Comment by richie5um** [comment]
Can you email me (rs@richsomerfield.com) including the email you used to purchase and I’ll send your you license code? If you can’t remember the email, just send me a email anyway and I’ll get you up and running ASAP.

**Comment by reibejoy** [comment]
Thanks, I just wrote you a mail.
