### ISSUE TITLE
Icon & Separators

### ISSUE THREAD

**Issue by defrilitus** [richie5um/TextBar-Recipes#68]
I just discovered this great little app. Two quick questions:
- What is the "(undocumented) preference to hide TextBar icon in the menu" mentioned in the release notes?
- Is it possible to add a separator between two or more user items in the menu? If not, could you envisage adding this possibility in the next release?
Thanks in advance!

**Comment by richie5um** [comment]
Thanks. Glad you like it.

- The TextBar icon should auto-hide if there is one (or more) textbar item being shown. Is that not working?
- Hmm, I thought I'd added a separator but can't remember if I did. Let me check the code...

**Comment by richie5um** [comment]
Yep :)

![image](https://user-images.githubusercontent.com/907033/79347757-f3deaf00-7f2b-11ea-98b6-667b3db9489e.png)

If a line has only '----' on it, it'll show as a separator. i.e.
`echo 'Separator' && echo 'Hello' && echo '----' && echo 'World' && echo '----' && echo ':)'`

**Comment by defrilitus** [comment]
Thanks for your quick answer. The separator works perfectly.
With regard to the icon, I though that you were referring to the icon in the menu (above quit); but that's certainly not a great problem.
Time to buy the app ;-)
