### ISSUE TITLE
No text in menubar - just an icon and a dot

### ISSUE THREAD

**Issue by hepcat72** [richie5um/TextBar-Recipes#69]
My guess is that the script you're using doesn't have a shebang at the top, thus my default prefered shell is trying to run your bash script to generate the text?  Because this is what I see:

<img width="772" alt="textbarbug" src="https://user-images.githubusercontent.com/2300532/83283687-9afc6a80-a1a9-11ea-83b5-932676a79e9d.png">

Is there a work-around to get it to work without me changing my default shell?

**Comment by richie5um** [comment]
Hi. Can you replace those with your own script files - to verify your hypothesis? Thanks.

Let me know if that doesnt make sense :)

**Comment by hepcat72** [comment]
No, that wasn't it. Apparently the default shell in the advanced prefs defaults to the user's default shell, but the default "Shell Arguments" value (`-l`) is bash-specific. Removing the invalid `-l` (or editing the default shell to bash) fixes the problem.

**Comment by hepcat72** [comment]
Whoops. It doesn't fix everything.  I'm guessing that the local IP address option must add another bash-specific argument? It still displays as a dot.

**Comment by richie5um** [comment]
Can you try editing some of the values on the 'Preferences > Settings' tab? Changing the shell and launch options may help. Just to see if we can narrow it down.

It also logs out to Console.log.

**Comment by hepcat72** [comment]
Yeah, I saw that.  I enabled it briefly before I figured out the issue with the shell.  I just encountered another issue. Perhaps it's related... I tried changing the font to look like what I'm used to, but all the changes are only applied to the external IP item and not the whoami item... I'll re-enable logging and take a look.

**Comment by richie5um** [comment]
Sorry, I'd missed your earlier comment. The local IP checks a specific adaptor, it could be the wrong one for your device.

**Comment by richie5um** [comment]
Ok, thanks.

**Comment by richie5um** [comment]
No ideal. But, sounds like it eventually works. Correct?

**Comment by hepcat72** [comment]
Yeah.

**Comment by hepcat72** [comment]
OK, so I looked in the console.  Every other TextBar line has this error:

`default	14:40:45.668523-0400	TextBar	Script output error: PATH: Undefined variable.`

Not sure why, as PATH is defined in both bash and in tcsh:

```
tcsh>echo $PATH
/opt/sw/bin:/opt/sw/sbin:~/local/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
tcsh>bash
bash-5.0$ echo $PATH
/opt/sw/bin:/opt/sw/sbin:~/local/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
```

**Comment by hepcat72** [comment]
I've been trying to add the local IP address.  I ran into another issue.  It does appear that another bash argument is added which I cannot edit.  Switching the default shell to bash fixes that.  It's worth noting that the example in your README for the DHCP address spits out the en5 address (although once I got the default local IP address option working, it was correct).  But the other bug I encountered is that when you add a new item to the menu bar, their positions change around.  I was putting the whoami output where "fast user switching" would be (since my university restricts that system pref and I like having that there).  But when I added new items, the external IP would change places with whoami.

**Comment by richie5um** [comment]
The order of the items in the TextBar preferences list is intended to be reflected in the menubar. You can drag/drop the items in the list :).

**Comment by hepcat72** [comment]
Yes, but adding a new item changes the order of the previously manually positioned items. Also, I'm seeing randomly, other items are changing positions after a sleep/wake cycle (when I close the laptop lid and re-open it later).  Specifically, my AirPlay menu item shifts.  I don't recall specifically where I was finding it, but it was something like this:

Before closing the lid (the order I manually set):

<img width="737" alt="textbar-before-sleep" src="https://user-images.githubusercontent.com/2300532/83539277-d312ee80-a4c4-11ea-83d9-997b433d26ef.png">

After re-opening the lid:

<img width="736" alt="textbar-changed-after-sleep-wake" src="https://user-images.githubusercontent.com/2300532/83539302-db6b2980-a4c4-11ea-8c45-fd294303b3d8.png">

I guess I should be submitting these as separate issues...

**Comment by richie5um** [comment]
Are you re-positioning TextBar items using the macOS mechanism (hold command, click and drag icon)? If so, don't do that to reposition TextBar items - instead reposition the items in the TextBar Preferences list. TextBar isn't allowed to get access (or edit) the macOS ordering approach.

**Comment by hepcat72** [comment]
Yes, though I don't see the ability to place the whoami item where I want it (between time & spotlight). I take it that's not possible without command-drag?

**Comment by richie5um** [comment]
You can use command-drag, but, it won't persist on reboot.
