### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by kerim** [richie5um/TextBar-Recipes#8]
Great app, but I have two requests for the preferences pane:
1. A description/name field. It can be hard to tell what script is what from just the small snippet of code. It would be nice to give it a name.
2. The ability to display scripts in a larger text box for editing. It is hard to scroll through the text.

Also, sometimes the text goes white on white. Clicking elsewhere and then inside the box fixes it, but seems like a bug.

**Comment by richie5um** [comment]
Thanks.

I’ve been contemplating having a different UI to make the scripts easier to create/edit/view/manage/run. But, I’ve not managed to think of a good solution.

If you have any other apps that you think would be a good source of inspiration, please let me know.


Regards,
-Rich

**Comment by kerim** [comment]
You might look at various text expander type apps to see how they handle it. I use Typinator, which isn't pretty, but gets the job done. (Note, it also has "sets" which makes the whole interface much more complex than you would need.)

![](https://www.evernote.com/shard/s1/sh/1c858f31-b97c-4830-af21-e7c8b2f126bb/16f6e99f0e47cc68de809a40e987096b/deep/0/Typinator.png)

**Comment by richie5um** [comment]
Hi,

Thanks. Good idea, I'll take a look.

I use Keyboard Maestro, but that feels way more complex than I wanted for TextBar.

-Rich
