### ISSUE TITLE
Edited an script and app won't open anymore

### ISSUE THREAD

**Issue by jeronimosodero** [richie5um/TextBar-Recipes#86]
I edited the default free space script and added a floppy disk emoji and the app keeps crashing when I open it. I tried re-installing but the same. I can't find where those scripts are saved. Thanks.

**Comment by richie5um** [comment]
Hi.

There are three locations for TextBar information...

Scripts + Preferences are stored is this plist file:
`~/Library/Preferences/com.RichSomerfield.TextBar.plist`

Scripts (and images) for Imported TextBar actions are stored here:
`~/Library/Application\ Support/TextBar`

So you could delete (or, move) those files. Alternatively, you can try running this, and then launch the app - as that may help keep your scripts but without them being enabled on launch:
`defaults write com.RichSomerfield.TextBar DisableItemsOnStart -bool true`

Hopefully this information helps.

Best,
Rich

**Comment by jeronimosodero** [comment]
the last command and editing the script from the preferences worked! thank you

**Comment by richie5um** [comment]
Good to hear. Thanks for letting me know.
