### ISSUE TITLE
Number of Mounted Volumes

### ISSUE THREAD

**Issue by kerim** [richie5um/TextBar-Recipes#9]
The various scripts I saw for listing the number of mounted volumes didn't work for me, so I came up with this one:

````
echo "HD# "`ls /Volumes/ | wc -l`
````

**Comment by richie5um** [comment]
:-) 

Much simpler. Thanks.

-Rich

**Comment by EDu-mac** [comment]
You can try this (only devices connected) 

diskutil list | grep '*' | grep -Ev 'disk0|Apple' | awk 'END {if (NR>0) print NR " devices"; else print "devices"}'

**Comment by richie5um** [comment]
Closing as there doesn't seem to be a 100% reliable way of getting the mounted volumes. Using 'ls /Volumes | wc -l' is very close, and simple, but it'll include the local drive.
