### ISSUE TITLE
Code signing needs to be updated?

### ISSUE THREAD

**Issue by dmarmor** [richie5um/TextBar-Recipes#90]
Hi! Are you still actively developing TextBar? I'm very keen to try it, as I can see so many many uses for it, but it appears the codesigning is out of date. I get the following Gatekeeper warning:

> **“TextBar.app” can’t be opened because Apple cannot check it for malicious software.**
> This software needs to be updated. Contact the developer for more information.

I'm running macOS 14.0 (Sonoma) on a 2021 MacBook Pro M1 Max.

Thank you!

**Comment by richie5um** [comment]
Hi. Yeah, unfortunately my mac with the codesign cert got wiped. And then for some annoying reason, I can't get the new cert to sign it correctly - it keeps reverting to the old one. I spent ages trying to fix it and have basically given up.

I don't really get any more sales, so I've been thinking about open sourcing the code for a long time.

**Comment by raguay** [comment]
I've loved using TextBar, but I never got it to work on my MacBook Pro M1 system. So, I did create an open source alternative for my use that is on GitHub:  https://github.com/raguay/scriptbarapp

It doesn't put the script outputs in the menu bar, but in a program window that has tabs. It works with my https://github.com/raguay/emailit application to run TextBar compatible scripts. It runs on my system 24/7 for a while now with no problems. I have plans to support xBar scripts as well (that is another open source program that works like TextBar), and to have it on Linux and Windows.

Richie, I'm sorry your having the issues. I've loved using TextBar all these years. Thanks for a great program.

**Comment by dmarmor** [comment]
Sorry to hear about the codesigning problems, @richie5um. If you do open source the code, I hope you'll mention it here, as I'd love to take a look and see if it's something I'd have the wherewithal to revive and maintain as an open source project.

Meantime, thank you @raguay for the links to your project. I'll check it out!

**Comment by richie5um** [comment]
Thanks both. 

Im 99% sure im gonna open source, just need to find some time to clean the git history and republish to GitHub. The code isn’t great, but I’m sure everyone says and feels that :-/.

**Comment by richie5um** [comment]
Happy Holidays 🎄 ... https://github.com/richie5um/TextBar
